### ISSUE TITLE
Please add support for `Microsoft Office 365` files 

### ISSUE THREAD

**Issue by hemangjoshi37a** [modelcontextprotocol/servers#172]
I want to access the content of the excel and word files in the MCP and currently there seems to be no suport for this . 

Development in this direction is much appreciated .

Thanks

**Comment by jspahrsummers** [comment]
We've now made [some changes](https://github.com/orgs/modelcontextprotocol/discussions/61) to how we'll manage the servers repo going forward.

**TLDR:** We're restructuring the MCP [servers](https://github.com/modelcontextprotocol/servers) repository to focus on reference implementations only. New server implementations should be developed in separate repositories and can be added as links to our README, rather than submitted as PRs to this repository.

In line with that new approach, I'll close this out, but we'd be happy to include a link to this server if it's built in another repo. Please do submit a PR when it's ready!
