### ISSUE TITLE
MCP Servers does work on my MacOS

### ISSUE THREAD

**Issue by ukalpa** [modelcontextprotocol/servers#293]
**Describe the bug**
Added postgresql and sqlite severs following the quickstart, I can see them in the Settings / Developer panel, however, unable to access their data in Claude AI Desktop and returned the error info "Could not attach to MCP server sqlite".
I confirm the test.db is a valid sqlite DB by accessing its data using sqlite3 command successfully. 

**To Reproduce**
1. Download and install Claude Ai Desktop
2. Create and edit /Users/ukalpa/Library/Application Support/Claude/claude_desktop_config.json with following content:
`{
  "mcpServers": {
    "postgres": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-postgres",
        "postgresql://postgres:postgres@localhost:15432/test"
      ]
    },
    "sqlite": {
      "command": "uvx",
      "args": ["mcp-server-sqlite", "--db-path", "/Users/ukalpa/test.db"]
    }
  }
}
`
3. Then quit and restart Calude App, fill in search db by the official quickstart prompt, get the error message as the graphic 1 shows.
![Screenshot 2024-12-10 at 19 33 49](https://github.com/user-attachments/assets/4b511868-b69b-40bf-927b-b883f38a6cc1)

**Expected behavior**
According to the quickstart, App should be able to access PostgreSQL or SQLite.

** Log **
Please see the graphic 2 here:
![Screenshot 2024-12-10 at 19 50 50](https://github.com/user-attachments/assets/f71fad36-e17e-4590-8290-db97e19e9664)

**Additional context**
My OS info:
Macbook Pro 2019 , macOS: 15.1.1 (24B91)

**Comment by jexp** [comment]
I have exactly the same issue, our mcp-neo4j-cypher server used to work all the time, with really great results, and suddenly it's not available to Claude anymore, although the MCP log shows, that it's started:

```
2024-12-11T15:07:09.228Z [info] Attempting to connect to MCP server movies-neo4j...
2024-12-11T15:07:09.238Z [info] Connected to MCP server movies-neo4j!
```

Config is still there.

<img width="760" alt="Bildschirmfoto 2024-12-11 um 16 18 54" src="https://github.com/user-attachments/assets/ee5448ac-6727-4a06-9ced-92fcf34975d0" />

Also claude is not showing the double-plug anymore to get access to the servers, it used to be there with the upload / google drive buttons.

![Bildschirmfoto 2024-12-11 um 16 10 44](https://github.com/user-attachments/assets/4d876768-556a-48ec-8cc9-e28e099f3840)

**Comment by cannavis** [comment]
mine either... 
<img width="1203" alt="Screenshot 2024-12-11 at 10 43 54 PM" src="https://github.com/user-attachments/assets/c499a6d1-fdfe-47b7-b977-7b6b796d1bbb" />

**Comment by ryan81g** [comment]
I had to update python to 3.12, restarted and Claude connected to the the SQLite MCP.

**Comment by burvall** [comment]
It seems likely that the issue is related to NVM (Node Version Manager). Here’s how you can resolve it step-by-step:

Steps to Fix the Issue:
	1.	Locate Node.js Installation
Open your terminal and run the following command to find out where Node.js is installed:

which node

This command will return the full path to the Node.js binary managed by NVM.

	2.	Install the MCP Server Globally
Use npm to install the MCP server globally. For example, to install the Puppeteer-based server:

npm install -g @modelcontextprotocol/server-puppeteer

This will make the server accessible globally on your system.

	3.	Find the Installed MCP Server Path
The MCP server files, including the index.js file, will typically be located in the following directory:

XXX/versions/node/v23.3.0/lib/node_modules/@modelcontextprotocol/server-puppeteer

Replace XXX with the path where NVM is installed on your system. For example, this might be /home/username/.nvm or /SSD-SYSTEM/NVM depending on your configuration.

	4.	Update Claude_desktop_config.json
Modify your Claude_desktop_config.json file to explicitly point to the Node.js executable managed by NVM and the MCP server’s index.js. Remove or replace the default configuration, which might look like this:

"puppeteer": {
   "command": "npx",
   "args": ["-y", "@modelcontextprotocol/server-puppeteer"]
}

with

"puppeteer": {
   "command": "/SSD-SYSTEM/NVM/versions/node/v23.3.0/bin/node",
   "args": ["/SSD-SYSTEM/NVM/versions/node/v23.3.0/lib/node_modules/@modelcontextprotocol/server-puppeteer/dist/index.js"]
}

Here, the command points to the specific Node.js binary, and the args list includes the full path to the MCP server’s entry file.

By directly specifying the paths, you avoid relying on npx, which may fail if there are version or configuration issues.

	5.	Restart Claude
Close and re-open Claude. The application should now automatically detect the installed servers based on your updated configuration.

Example Claude_desktop_config.json

Here’s a complete example of how your configuration file might look after the updates. Make sure to replace XXX or other placeholders with the actual paths and credentials:

{
  "mcpServers": {
    "filesystem": {
      "command": "/SSD-SYSTEM/NVM/versions/node/v23.3.0/bin/node",
      "args": ["/SSD-SYSTEM/NVM/versions/node/v23.3.0/lib/node_modules/@modelcontextprotocol/server-filesystem/dist/index.js",
        "/Users/xxx/Documents/Obsidian"
      ]
    },
    "github": {
      "command": "/SSD-SYSTEM/NVM/versions/node/v23.3.0/bin/node",
      "args": [
        "/SSD-SYSTEM/NVM/versions/node/v23.3.0/lib/node_modules/@modelcontextprotocol/server-github/dist/index.js"
      ],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "xxx"
      }
    },
    "fetch": {
      "command": "uvx",
      "args": [
        "mcp-server-fetch"
      ]
    },
    "sqlite": {
      "command": "uvx",
      "args": ["mcp-server-sqlite", "--db-path", "~/test.db"]
    },
    "brave-search": {
      "command": "/SSD-SYSTEM/NVM/versions/node/v23.3.0/bin/node",
      "args": ["/SSD-SYSTEM/NVM/versions/node/v23.3.0/lib/node_modules/@modelcontextprotocol/server-brave-search/dist/index.js"],
      "env": {"BRAVE_API_KEY": "xxx"}
    },
    "puppeteer": {
      "command": "/SSD-SYSTEM/NVM/versions/node/v23.3.0/bin/node",
      "args": ["/SSD-SYSTEM/NVM/versions/node/v23.3.0/lib/node_modules/@modelcontextprotocol/server-puppeteer/dist/index.js"]
    },
    "memory": {
      "command": "/SSD-SYSTEM/NVM/versions/node/v23.3.0/bin/node",
      "args": [
        "/SSD-SYSTEM/NVM/versions/node/v23.3.0/lib/node_modules/@modelcontextprotocol/server-memory/dist/index.js"
      ]
    }
  }
}

By following these steps, you ensure that Claude has a properly configured environment, and all servers can be detected and used without relying on npx or encountering version conflicts with NVM.

**Comment by ukalpa** [comment]
Thanks a lot for your replies. Yes I found the issues were encountered by low node (v10) and python(3.9.x) versions on my macOS.  After upgraded them the MCP Servers are working fine now.
