### ISSUE TITLE
Need AWS S3 MCP Server

### ISSUE THREAD

**Issue by tech4life87** [modelcontextprotocol/servers#41]

**Comment by tech4life87** [comment]
I am willing to contribute to this

**Comment by jspahrsummers** [comment]
That'd be amazing! We'd be happy to review an S3 server. 🙂

**Comment by tech4life87** [comment]
> That'd be amazing! We'd be happy to review an S3 server. 🙂

perfect! on it

**Comment by jspahrsummers** [comment]
We've now made [some changes](https://github.com/orgs/modelcontextprotocol/discussions/61) to how we'll manage the servers repo going forward.

**TLDR:** We're restructuring the MCP [servers](https://github.com/modelcontextprotocol/servers) repository to focus on reference implementations only. New server implementations should be developed in separate repositories and can be added as links to our README, rather than submitted as PRs to this repository.

In line with that new approach, I'll close this request out, but we'd be happy to include a link to this server if it's built in another repo. Please do submit a PR when it's ready!
